# Generated by Django 4.1.3 on 2024-08-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
