# Generated by Django 4.1.3 on 2024-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_audiencestatus_remove_audience_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswallet',
            name='number_bb',
            field=models.FloatField(),
        ),
    ]
