# Generated by Django 4.1.3 on 2024-08-20 01:48

from django.db import migrations, models
import pandas as pd


def create_from_excel_audiences_users_wallets(apps, schema_editor):
    """Заполняет таблицу базовыми значениями, забитыми в эксель файле"""
    """Заполняется: Аудитории, Кошельки"""
    audiences = pd.read_excel("start_data.xlsx", sheet_name="Аудитории")
    users_wallets = pd.read_excel("start_data.xlsx", sheet_name="Кошельки")

    # Создаем аудитории для бронирования
    Building = apps.get_model('main', 'Building')
    AudienceStatus = apps.get_model('main', 'AudienceStatus')
    Audience = apps.get_model('main', 'Audience')
    for audience in audiences.values:
        build = Building.objects.get(name=audience[1], institute__name=audience[0])
        audience_status = AudienceStatus.objects.get(name=audience[4])
        _audience = Audience.objects.create(
            number=str(audience[2]),
            description=audience[3],
            building=build,
            audience_status=audience_status,
            number_of_users=audience[5])

    # Кошельки для оплаты бронирования
    UsersWallet = apps.get_model('main', 'UsersWallet')
    for wallet in users_wallets.values:
        _users_wallet = UsersWallet.objects.create(
            username=wallet[0],
            token=wallet[1],
            number_bb=wallet[2])


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_create_default_3'),
    ]

    operations = [
        migrations.RunPython(create_from_excel_audiences_users_wallets),
    ]
