# Generated by Django 4.1.3 on 2024-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aud'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswallet',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
