# Generated by Django 4.1.3 on 2024-10-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userswallet_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_slot',
            field=models.IntegerField(default=0),
        ),
    ]
