# Generated by Django 4.1.3 on 2024-10-14 20:52

import django.contrib.postgres.fields
from django.db import migrations, models
import pandas as pd
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistory',
            name='pair',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, max_length=8, null=True, size=None), blank=True, max_length=20, null=True, size=None),
        ),
    ]

