# Generated by Django 4.1.3 on 2024-10-20 19:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_load_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='week_pairs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, max_length=8, null=True, size=None), blank=True, max_length=20, null=True, size=None), blank=True, max_length=7, null=True, size=None),
        ),
    ]
