# Generated by Django 4.1.3 on 2024-08-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='access_list',
            field=models.ManyToManyField(to='main.access'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(to='main.preferences'),
        ),
    ]
