# Generated by Django 4.1.3 on 2024-08-20 01:48

from django.db import migrations, models
import pandas as pd


def create_from_excel_access_institute_preferences(apps, schema_editor):
    """Заполняет таблицу базовыми значениями, забитыми в эксель файле"""
    """Заполняется: Институты, Здания, Статусы"""
    access_list = pd.read_excel("start_data.xlsx", sheet_name="Доступы")
    institutes = pd.read_excel("start_data.xlsx", sheet_name="Институты")
    preferenceses = pd.read_excel("start_data.xlsx", sheet_name="Предпочтения")

    # Создаём список поддерживаемых институтов
    Access = apps.get_model('main', 'Access')
    for access in access_list.values:
        _access = Access.objects.create(
            description=access[0])

    # Создаём здания для созданный ранее институтов
    Institute = apps.get_model('main', 'Institute')
    for institute in institutes.values:
        _institute = Institute.objects.create(
            name=institute[0],
            description=institute[1])

    # Создаем список статусов бронирования
    Preferences = apps.get_model('main', 'Preferences')
    for preferences in preferenceses.values:
        _preferences = Preferences.objects.create(
            name=preferences[0],
            description=preferences[1])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_from_excel_access_institute_preferences),
    ]
