# Generated by Django 4.1.3 on 2024-08-20 01:48

from django.db import migrations, models
import pandas as pd


def create_from_excel_role_institute_group(apps, schema_editor):
    """Заполняет таблицу базовыми значениями, забитыми в эксель файле"""
    """Заполняется: Роли, Институтские группы"""
    roles = pd.read_excel("start_data.xlsx", sheet_name="Роли")
    institute_groups = pd.read_excel("start_data.xlsx", sheet_name="Группы")

    # Роли
    Role = apps.get_model('main', 'Role')
    InstituteGroup = apps.get_model('main', 'InstituteGroup')
    Institute = apps.get_model('main', 'Institute')
    for role in roles.values:
        _role = Role.objects.create(
            name=role[0],
            description=role[1])

    # Институтские группы
    for institute_group in institute_groups.values:
        institute = Institute.objects.get(name=institute_group[2])
        _institute_group = InstituteGroup.objects.create(
            name=institute_group[0],
            description=institute_group[1],
            institute=institute)


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_reaf_from_excel_1'),
    ]

    operations = [
        migrations.RunPython(create_from_excel_role_institute_group),
    ]
